# Generated by Django 4.2.27 on 2026-07-09 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import employees.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matricula",
                    models.CharField(max_length=50, verbose_name="Matrícula"),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=255, verbose_name="Nome Completo"),
                ),
                (
                    "cpf",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[employees.models.validate_cpf],
                        verbose_name="CPF",
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("TURNO_1", "1º Turno"),
                            ("TURNO_2", "2º Turno"),
                            ("TURNO_3", "3º Turno"),
                            ("ADM", "Administrativo"),
                        ],
                        default="ADM",
                        max_length=20,
                        verbose_name="Turno",
                    ),
                ),
                ("data_admissao", models.DateField(verbose_name="Data de Admissão")),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("ATIVO", "Ativo"),
                            ("AFASTADO", "Afastado"),
                            ("DESLIGADO", "Desligado"),
                        ],
                        default="ATIVO",
                        max_length=20,
                        verbose_name="Situação Cadastral",
                    ),
                ),
                (
                    "data_desligamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Desligamento"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "tamanho_camisa",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Tamanho da Camisa",
                    ),
                ),
                (
                    "tamanho_calca",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Tamanho da Calça",
                    ),
                ),
                (
                    "num_calcado",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Numeração do Calçado"
                    ),
                ),
                (
                    "tamanho_luva",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Tamanho da Luva",
                    ),
                ),
                (
                    "modelo_farda",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Modelo de Farda",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observações Operacionais"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "centro_custo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="organizations.costcenter",
                        verbose_name="Centro de Custo",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="organizations.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_employees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "funcao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="organizations.function",
                        verbose_name="Função/Cargo",
                    ),
                ),
                (
                    "setor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="organizations.sector",
                        verbose_name="Setor",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="organizations.unit",
                        verbose_name="Unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colaborador",
                "verbose_name_plural": "Colaboradores",
                "unique_together": {("company", "matricula")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Início"
                    ),
                ),
                (
                    "data_fim",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Fim"
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "alterado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Alterado por",
                    ),
                ),
                (
                    "centro_custo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.costcenter",
                        verbose_name="Centro de Custo",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="employees.employee",
                        verbose_name="Colaborador",
                    ),
                ),
                (
                    "funcao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.function",
                        verbose_name="Função/Cargo",
                    ),
                ),
                (
                    "setor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.sector",
                        verbose_name="Setor",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.unit",
                        verbose_name="Unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Colaborador",
                "verbose_name_plural": "Históricos de Colaboradores",
                "ordering": ["-data_inicio"],
            },
        ),
    ]
