# Generated by Django 5.2.16 on 2026-09-03 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('organizations', '0002_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='funcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organizations.function', verbose_name='Função/Cargo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='funcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.function', verbose_name='Função/Cargo'),
        ),
    ]
