# Generated by Django 4.2.27 on 2026-07-09 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("employees", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificadoAprovacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Número Normalizado (Dígitos)",
                    ),
                ),
                (
                    "numero_exibicao",
                    models.CharField(
                        max_length=50, verbose_name="Número de Exibição (ex: CA 12345)"
                    ),
                ),
                (
                    "equipamento",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Descrição Oficial do Equipamento",
                    ),
                ),
                (
                    "fabricante",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Fabricante/Importador Oficial",
                    ),
                ),
                (
                    "natureza_protecao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Natureza da Proteção"
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Situação do C.A.",
                    ),
                ),
                (
                    "data_emissao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Emissão"
                    ),
                ),
                (
                    "data_validade",
                    models.DateField(verbose_name="Data de Validade do C.A."),
                ),
                (
                    "fonte",
                    models.CharField(
                        default="CAEPI_MTE",
                        max_length=100,
                        verbose_name="Fonte de Dados",
                    ),
                ),
                (
                    "ultima_sincronizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Sincronização"
                    ),
                ),
                (
                    "status_verificacao",
                    models.CharField(
                        choices=[
                            (
                                "VERIFICADO_BASE_OFICIAL",
                                "Verificado na Base Oficial CAEPI",
                            ),
                            (
                                "INFORMADO_MANUALMENTE",
                                "Informado Manualmente (com justificativa)",
                            ),
                            ("NAO_ENCONTRADO", "Não Encontrado na Base MTE"),
                            ("DESATUALIZADO", "Desatualizado"),
                        ],
                        default="INFORMADO_MANUALMENTE",
                        max_length=30,
                        verbose_name="Status de Verificação",
                    ),
                ),
                (
                    "justificativa_manual",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Justificativa (Se cadastrado manualmente)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado de Aprovação (C.A.)",
                "verbose_name_plural": "Certificados de Aprovação (C.A.)",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome do EPI")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("PROTECAO_CABECA", "Proteção da Cabeça"),
                            ("PROTECAO_AUDITIVA", "Proteção Auditiva"),
                            ("PROTECAO_RESPIRATORIA", "Proteção Respiratória"),
                            ("PROTECAO_OCULAR", "Proteção Ocular e Facial"),
                            ("PROTECAO_TRONCO", "Proteção do Tronco"),
                            ("PROTECAO_MEMBROS_SUP", "Proteção dos Membros Superiores"),
                            ("PROTECAO_MEMBROS_INF", "Proteção dos Membros Inferiores"),
                            ("VESTUARIO", "Vestuário / Fardamento"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=50,
                        verbose_name="Categoria de Proteção",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "unidade_medida",
                    models.CharField(
                        default="UND", max_length=20, verbose_name="Unidade de Medida"
                    ),
                ),
                (
                    "fabricante",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Fabricante Padrão",
                    ),
                ),
                (
                    "exige_ca",
                    models.BooleanField(
                        default=True,
                        verbose_name="Exige C.A. (Certificado de Aprovação)",
                    ),
                ),
                (
                    "controlado_individualmente",
                    models.BooleanField(
                        default=True, verbose_name="Controlado Individualmente"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "EPI / Produto",
                "verbose_name_plural": "EPIs / Produtos",
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tamanho",
                    models.CharField(
                        default="U",
                        max_length=20,
                        verbose_name="Tamanho/Numeração/Grade",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="SKU / Código Interno",
                    ),
                ),
                (
                    "codigo_barras",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Código de Barras",
                    ),
                ),
                (
                    "estoque_minimo",
                    models.IntegerField(default=0, verbose_name="Estoque Mínimo"),
                ),
                (
                    "estoque_maximo",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Estoque Máximo"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="ppe.product",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variante de EPI",
                "verbose_name_plural": "Variantes de EPI",
                "unique_together": {("product", "tamanho")},
            },
        ),
        migrations.CreateModel(
            name="PPEDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "validade_fisica",
                    models.DateField(verbose_name="Validade Física do Lote"),
                ),
                ("quantidade", models.IntegerField(verbose_name="Quantidade Entregue")),
                (
                    "custo_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Custo Unitário da Compra",
                    ),
                ),
                ("data_entrega", models.DateField(verbose_name="Data de Fornecimento")),
                (
                    "vida_util_aplicada",
                    models.IntegerField(verbose_name="Vida Útil Aplicada (Dias)"),
                ),
                (
                    "data_prevista_troca",
                    models.DateField(verbose_name="Próxima Troca Prevista"),
                ),
                (
                    "origem_necessidade",
                    models.CharField(
                        choices=[
                            ("MATRIZ", "Matriz da Função"),
                            ("EXTRAORDINARIA", "EPI Extraordinário"),
                        ],
                        default="MATRIZ",
                        max_length=20,
                        verbose_name="Origem da Necessidade",
                    ),
                ),
                (
                    "natureza_entrega",
                    models.CharField(
                        choices=[
                            ("INICIAL", "Entrega Inicial"),
                            ("SUBSTITUICAO_VIDA_UTIL", "Substituição por Vida Útil"),
                            ("DANO", "Substituição por Dano"),
                            ("EXTRAVIO", "Substituição por Extravio/Perda"),
                            ("MUDANCA_FUNCAO", "Mudança de Função/Setor"),
                            ("EXTRAORDINARIA", "Necessidade Extraordinária"),
                            ("OUTRA", "Outra"),
                        ],
                        default="INICIAL",
                        max_length=30,
                        verbose_name="Natureza da Entrega",
                    ),
                ),
                (
                    "motivo_substituicao",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Motivo de Substituição/Observações",
                    ),
                ),
                (
                    "nome_trabalhador_confirmacao",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nome de Confirmação",
                    ),
                ),
                (
                    "confirmacao_data_hora",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data/Hora da Ciência"
                    ),
                ),
                (
                    "recibo_hash",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Hash do Recibo",
                    ),
                ),
                (
                    "status_assinatura",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente de Ciência"),
                            ("ASSINADO", "Ciência Confirmada"),
                            ("REJEITADO", "Rejeitado pelo Colaborador"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Status da Ciência",
                    ),
                ),
                (
                    "ca_entregue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ppe.certificadoaprovacao",
                        verbose_name="C.A. Entregue",
                    ),
                ),
                (
                    "centro_custo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.costcenter",
                        verbose_name="Centro de Custo no Momento da Entrega",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ppe_deliveries",
                        to="employees.employee",
                        verbose_name="Colaborador",
                    ),
                ),
                (
                    "funcao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.function",
                        verbose_name="Função no Momento da Entrega",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.lot",
                        verbose_name="Lote do Fabricante",
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ppe.productvariant",
                        verbose_name="EPI Entregue (Variante)",
                    ),
                ),
                (
                    "setor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.sector",
                        verbose_name="Setor no Momento da Entrega",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.unit",
                        verbose_name="Unidade no Momento da Entrega",
                    ),
                ),
                (
                    "usuario_responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsible_deliveries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Técnico/Entregador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrega de EPI",
                "verbose_name_plural": "Entregas de EPIs",
                "ordering": ["-data_entrega"],
            },
        ),
        migrations.CreateModel(
            name="ExtraordinaryPPE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motivo",
                    models.TextField(
                        verbose_name="Motivo do Fornecimento Extraordinário"
                    ),
                ),
                (
                    "atividade_risco",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Atividade Temporária ou Risco Específico",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(verbose_name="Data Inicial de Vigência"),
                ),
                (
                    "data_fim",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Final de Vigência"
                    ),
                ),
                (
                    "quantidade",
                    models.IntegerField(default=1, verbose_name="Quantidade"),
                ),
                (
                    "vida_util_dias",
                    models.IntegerField(verbose_name="Vida Útil/Prazo de Troca (Dias)"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "autorizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autorizado por",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraordinary_ppes",
                        to="employees.employee",
                        verbose_name="Colaborador",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ppe.product",
                        verbose_name="EPI",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ppe.productvariant",
                        verbose_name="Variante",
                    ),
                ),
            ],
            options={
                "verbose_name": "EPI Extraordinário",
                "verbose_name_plural": "EPIs Extraordinários",
            },
        ),
        migrations.CreateModel(
            name="PPEMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "obrigatorio",
                    models.BooleanField(default=True, verbose_name="Obrigatório"),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=True, verbose_name="EPI Principal da Função"
                    ),
                ),
                (
                    "quantidade_padrao",
                    models.IntegerField(default=1, verbose_name="Quantidade Padrão"),
                ),
                (
                    "vida_util_dias",
                    models.IntegerField(verbose_name="Vida Útil Padrão (Dias)"),
                ),
                (
                    "prazo_troca_preventiva",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Prazo de Troca Preventiva (Dias)",
                    ),
                ),
                (
                    "orientacoes",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Orientações e Instruções de Uso",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "funcao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ppe_matrix_entries",
                        to="organizations.function",
                        verbose_name="Função/Cargo",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ppe.product",
                        verbose_name="EPI",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ppe.productvariant",
                        verbose_name="Variante Específica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matriz de EPI por Função",
                "verbose_name_plural": "Matrizes de EPI por Função",
                "unique_together": {("funcao", "product")},
            },
        ),
    ]
