# Generated by Django 5.2.16 on 2026-07-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ca_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='C.A. (Certificado de Aprovação)'),
        ),
        migrations.AddField(
            model_name='product',
            name='tipo_produto',
            field=models.CharField(choices=[('EPI', 'EPI'), ('MATERIAL_SEGURANCA', 'Material de Segurança'), ('MATERIAL_CONSUMO', 'Material de Consumo'), ('FERRAMENTA', 'Ferramenta'), ('UNIFORME', 'Uniforme'), ('OUTRO', 'Outro')], default='EPI', max_length=50, verbose_name='Tipo de Produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categoria',
            field=models.CharField(blank=True, choices=[('PROTECAO_CABECA', 'Proteção da Cabeça'), ('PROTECAO_AUDITIVA', 'Proteção Auditiva'), ('PROTECAO_RESPIRATORIA', 'Proteção Respiratória'), ('PROTECAO_OCULAR', 'Proteção Ocular e Facial'), ('PROTECAO_TRONCO', 'Proteção do Tronco'), ('PROTECAO_MEMBROS_SUP', 'Proteção dos Membros Superiores'), ('PROTECAO_MEMBROS_INF', 'Proteção dos Membros Inferiores'), ('VESTUARIO', 'Vestuário / Fardamento'), ('OUTRO', 'Outro')], default='OUTRO', max_length=50, null=True, verbose_name='Categoria de Proteção'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Produto'),
        ),
    ]
