# Generated by Django 5.2.16 on 2026-07-13 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0002_product_ca_numero_product_tipo_produto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoaprovacao',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ do Fabricante/Importador'),
        ),
        migrations.AddField(
            model_name='certificadoaprovacao',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Restrições ou Observações'),
        ),
        migrations.AddField(
            model_name='certificadoaprovacao',
            name='presente_na_fonte',
            field=models.BooleanField(default=True, verbose_name='Presente na Fonte Oficial'),
        ),
        migrations.AddField(
            model_name='certificadoaprovacao',
            name='versao_importacao',
            field=models.BigIntegerField(default=0, verbose_name='Versão da Última Importação'),
        ),
        migrations.CreateModel(
            name='CAEPISyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora de Início')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Conclusão')),
                ('status', models.CharField(choices=[('INICIADO', 'Iniciado'), ('BAIXANDO', 'Baixando'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('CONCLUIDO_ALERTAS', 'Concluído com Alertas'), ('FALHOU', 'Falhou'), ('IGNORADO', 'Ignorado por não haver nova versão')], default='INICIADO', max_length=30, verbose_name='Status')),
                ('tipo_execucao', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICA', 'Automática')], default='MANUAL', max_length=20, verbose_name='Tipo de Execução')),
                ('fonte', models.CharField(max_length=255, verbose_name='Fonte Consultada')),
                ('arquivo_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Arquivo Processado')),
                ('arquivo_tamanho', models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho do Arquivo (Bytes)')),
                ('arquivo_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash SHA-256 do Arquivo')),
                ('total_lido', models.IntegerField(default=0, verbose_name='Total Lido')),
                ('total_valido', models.IntegerField(default=0, verbose_name='Total Válido')),
                ('total_invalido', models.IntegerField(default=0, verbose_name='Total Inválido')),
                ('total_criados', models.IntegerField(default=0, verbose_name='Total Criados')),
                ('total_atualizados', models.IntegerField(default=0, verbose_name='Total Atualizados')),
                ('total_inalterados', models.IntegerField(default=0, verbose_name='Total Inalterados')),
                ('total_desativados', models.IntegerField(default=0, verbose_name='Total Desativados')),
                ('erro_mensagem', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('traceback', models.TextField(blank=True, null=True, verbose_name='Traceback Técnico')),
                ('duracao_segundos', models.FloatField(blank=True, null=True, verbose_name='Duração (Segundos)')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Log de Sincronização CAEPI',
                'verbose_name_plural': 'Logs de Sincronização CAEPI',
                'ordering': ['-start_time'],
            },
        ),
    ]
