# Generated by Django 5.2.16 on 2026-07-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0003_certificadoaprovacao_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoaprovacao',
            name='aprovado_para',
            field=models.TextField(blank=True, null=True, verbose_name='Aprovado Para'),
        ),
        migrations.AddField(
            model_name='certificadoaprovacao',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='certificadoaprovacao',
            name='grupo_protecao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Grupo de Proteção'),
        ),
        migrations.AddField(
            model_name='certificadoaprovacao',
            name='natureza',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Natureza'),
        ),
        migrations.AddField(
            model_name='certificadoaprovacao',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AddField(
            model_name='certificadoaprovacao',
            name='processo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do Processo'),
        ),
        migrations.AddField(
            model_name='certificadoaprovacao',
            name='uf',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='UF'),
        ),
    ]
