# Generated by Django 5.2.16 on 2026-07-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0004_certificadoaprovacao_aprovado_para_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppedelivery',
            name='status_assinatura',
            field=models.CharField(choices=[('PENDENTE', 'Pendente de Ciência'), ('ASSINADO', 'Ciência Confirmada'), ('REJEITADO', 'Rejeitado pelo Colaborador'), ('REGISTRADO_OPERADOR', 'Registrado pelo Operador (Sem Assinatura)')], default='PENDENTE', max_length=20, verbose_name='Status da Ciência'),
        ),
    ]
