# Generated by Django 5.2.16 on 2026-09-03 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_company_options'),
        ('ppe', '0005_alter_ppedelivery_status_assinatura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorPPEMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EM_ELABORACAO', 'Em Elaboração'), ('ATIVA', 'Ativa')], default='EM_ELABORACAO', max_length=20, verbose_name='Status da Matriz')),
                ('ativado_em', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Ativação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração da Matriz do Setor',
                'verbose_name_plural': 'Configurações das Matrizes dos Setores',
            },
        ),
        migrations.AlterModelOptions(
            name='ppematrix',
            options={'verbose_name': 'Matriz de EPI', 'verbose_name_plural': 'Matrizes de EPI'},
        ),
        migrations.AlterUniqueTogether(
            name='ppematrix',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ppematrix',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ppe_matrix_entries', to='organizations.sector', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='ppedelivery',
            name='funcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.function', verbose_name='Função no Momento da Entrega'),
        ),
        migrations.AlterField(
            model_name='ppedelivery',
            name='origem_necessidade',
            field=models.CharField(choices=[('MATRIZ', 'Matriz do Setor'), ('FUNCAO_LEGADO', 'Matriz por Função (Legado)'), ('EXTRAORDINARIA', 'EPI Extraordinário')], default='MATRIZ', max_length=20, verbose_name='Origem da Necessidade'),
        ),
        migrations.AlterField(
            model_name='ppematrix',
            name='funcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ppe_matrix_entries', to='organizations.function', verbose_name='Função/Cargo (Legado)'),
        ),
        migrations.AlterField(
            model_name='ppematrix',
            name='principal',
            field=models.BooleanField(default=True, verbose_name='EPI Principal'),
        ),
        migrations.AddConstraint(
            model_name='ppematrix',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('funcao__isnull', True), ('setor__isnull', False)), models.Q(('funcao__isnull', False), ('setor__isnull', True)), _connector='OR'), name='check_matrix_setor_or_funcao_exclusive'),
        ),
        migrations.AddConstraint(
            model_name='ppematrix',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True), ('setor__isnull', False)), fields=('setor', 'product'), name='unique_ppe_matrix_setor_product_active'),
        ),
        migrations.AddConstraint(
            model_name='ppematrix',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True), ('funcao__isnull', False)), fields=('funcao', 'product'), name='unique_ppe_matrix_funcao_product_active'),
        ),
        migrations.AddField(
            model_name='sectorppematrix',
            name='ativado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_matrices', to=settings.AUTH_USER_MODEL, verbose_name='Ativado por'),
        ),
        migrations.AddField(
            model_name='sectorppematrix',
            name='sector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ppe_matrix_config', to='organizations.sector', verbose_name='Setor'),
        ),
    ]
