# Generated by Django 5.2 on 2026-09-04
import re
import unicodedata
from django.db import migrations, models


def canonical_size_key(tamanho):
    if not tamanho:
        return 'U'
    norm = unicodedata.normalize('NFKC', str(tamanho)).strip().upper()
    norm = re.sub(r'\s+', ' ', norm)
    if norm in ('UNICO', 'ÚNICO', 'U'):
        return 'U'
    return norm


def normalize_size_label(tamanho):
    key = canonical_size_key(tamanho)
    standard_labels = {
        'U': 'U',
        'PP': 'PP',
        'P': 'P',
        'M': 'M',
        'G': 'G',
        'GG': 'GG',
        'XG': 'XG',
        'XXG': 'XXG'
    }
    return standard_labels.get(key, key)


def cleanup_duplicate_variants_and_backfill(apps, schema_editor):
    Product = apps.get_model('ppe', 'Product')
    ProductVariant = apps.get_model('ppe', 'ProductVariant')
    Lot = apps.get_model('inventory', 'Lot')
    StockMovement = apps.get_model('inventory', 'StockMovement')
    StockTransferItem = apps.get_model('inventory', 'StockTransferItem')
    LocationStockMinimo = apps.get_model('inventory', 'LocationStockMinimo')
    PPEDelivery = apps.get_model('ppe', 'PPEDelivery')
    PPEMatrix = apps.get_model('ppe', 'PPEMatrix')
    ExtraordinaryPPE = apps.get_model('ppe', 'ExtraordinaryPPE')

    for product in Product.objects.all():
        variants = list(ProductVariant.objects.filter(product=product).order_by('id'))
        from collections import defaultdict
        grouped = defaultdict(list)
        for v in variants:
            key = canonical_size_key(v.tamanho)
            grouped[key].append(v)

        for key, v_list in grouped.items():
            if len(v_list) > 1:
                # Escolhe canônica: preferência por aquela cujo tamanho já é o label canônico
                canonical_label = normalize_size_label(key)
                canonical = None
                for candidate in v_list:
                    if candidate.tamanho == canonical_label:
                        canonical = candidate
                        break
                if not canonical:
                    canonical = v_list[0]

                # Reaponta referências das duplicadas para a canônica
                for dup in v_list:
                    if dup.id != canonical.id:
                        Lot.objects.filter(product_variant=dup).update(product_variant=canonical)
                        StockMovement.objects.filter(product_variant=dup).update(product_variant=canonical)
                        PPEDelivery.objects.filter(product_variant=dup).update(product_variant=canonical)
                        StockTransferItem.objects.filter(product_variant=dup).update(product_variant=canonical)
                        LocationStockMinimo.objects.filter(product_variant=dup).update(product_variant=canonical)
                        PPEMatrix.objects.filter(variant=dup).update(variant=canonical)
                        ExtraordinaryPPE.objects.filter(variant=dup).update(variant=canonical)
                        dup.delete()

                # Atualiza a canônica
                canonical.tamanho = normalize_size_label(canonical.tamanho)
                canonical.tamanho_normalizado = key
                canonical.save(update_fields=['tamanho', 'tamanho_normalizado'])
            elif len(v_list) == 1:
                single = v_list[0]
                single.tamanho = normalize_size_label(single.tamanho)
                single.tamanho_normalizado = key
                single.save(update_fields=['tamanho', 'tamanho_normalizado'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('ppe', '0006_sectorppematrix_alter_ppematrix_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='tamanho_normalizado',
            field=models.CharField(db_index=True, default='U', max_length=20, verbose_name='Chave Normalizada do Tamanho'),
        ),
        migrations.RunPython(
            cleanup_duplicate_variants_and_backfill,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'tamanho_normalizado'), name='unique_product_variant_normalized'),
        ),
    ]
