# Generated by Django 4.2.30 on 2026-09-04 17:08

from django.db import migrations, models


def normalize_existing_products(apps, schema_editor):
    Product = apps.get_model('ppe', 'Product')
    sinonimos = {
        'UND': 'UND', 'UN': 'UND', 'UNID': 'UND', 'UNIDADE': 'UND', 'UNIDADES': 'UND',
        'PAR': 'PAR', 'PARES': 'PAR',
        'CX': 'CX', 'CAIXA': 'CX', 'CAIXAS': 'CX',
        'PCT': 'PCT', 'PACOTE': 'PCT', 'PACOTES': 'PCT',
        'KIT': 'KIT', 'KITS': 'KIT',
        'CJ': 'CJ', 'CONJUNTO': 'CJ', 'CONJUNTOS': 'CJ',
        'M': 'M', 'METRO': 'M', 'METROS': 'M',
    }
    for p in Product.objects.all():
        changed = False
        if p.unidade_medida:
            u_clean = str(p.unidade_medida).strip().upper()
            u_norm = sinonimos.get(u_clean, 'UND')
            if p.unidade_medida != u_norm:
                p.unidade_medida = u_norm
                changed = True
        else:
            p.unidade_medida = 'UND'
            changed = True

        if p.ca_numero:
            num_clean = "".join([c for c in str(p.ca_numero) if c.isdigit()])
            if num_clean != p.ca_numero:
                p.ca_numero = num_clean if num_clean else None
                changed = True
        if changed:
            p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0007_productvariant_tamanho_normalizado_cleanup'),
    ]

    operations = [
        migrations.RunPython(normalize_existing_products, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='unidade_medida',
            field=models.CharField(choices=[('UND', 'UND — Unidade'), ('PAR', 'PAR — Par'), ('CX', 'CX — Caixa'), ('PCT', 'PCT — Pacote'), ('KIT', 'KIT — Kit'), ('CJ', 'CJ — Conjunto'), ('M', 'M — Metro')], default='UND', max_length=10, verbose_name='Unidade de Medida'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('ca_numero__isnull', False), models.Q(('ca_numero', ''), _negated=True)), fields=('ca_numero',), name='unique_product_ca_numero_not_empty'),
        ),
    ]
