# Generated by Django 4.2.27 on 2026-07-09 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razao_social",
                    models.CharField(max_length=255, verbose_name="Razão Social"),
                ),
                (
                    "nome_fantasia",
                    models.CharField(max_length=255, verbose_name="Nome Fantasia"),
                ),
                (
                    "cnpj",
                    models.CharField(max_length=18, unique=True, verbose_name="CNPJ"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código da Unidade"
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome da Unidade"),
                ),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                ("estado", models.CharField(max_length=2, verbose_name="UF")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="units",
                        to="organizations.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidade",
                "verbose_name_plural": "Unidades",
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome do Setor"),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código do Setor",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sectors",
                        to="organizations.unit",
                        verbose_name="Unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Setor",
                "verbose_name_plural": "Setores",
                "unique_together": {("unit", "nome")},
            },
        ),
        migrations.CreateModel(
            name="InventoryLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, verbose_name="Código do Local"),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome do Local"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ALMOXARIFADO", "Almoxarifado"),
                            ("SST", "Estoque SST"),
                            ("OUTRO", "Outro"),
                        ],
                        default="ALMOXARIFADO",
                        max_length=20,
                        verbose_name="Tipo de Local",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_locations",
                        to="organizations.unit",
                        verbose_name="Unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local de Estoque",
                "verbose_name_plural": "Locais de Estoque",
                "unique_together": {("unit", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="Function",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=255, verbose_name="Nome da Função/Cargo"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="functions",
                        to="organizations.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Função/Cargo",
                "verbose_name_plural": "Funções/Cargos",
                "unique_together": {("company", "nome")},
            },
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=50, verbose_name="Código do Centro de Custo"
                    ),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_centers",
                        to="organizations.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Centro de Custo",
                "verbose_name_plural": "Centros de Custo",
                "unique_together": {("company", "codigo")},
            },
        ),
    ]
