# Generated by Django 5.2.16 on 2026-07-14 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': [('can_force_cascade_delete', 'Pode forçar a exclusão em cascata de registros')], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
