# Generated by Django 4.2.27 on 2026-07-09 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FiscalNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        max_length=50, verbose_name="Número da Nota Fiscal"
                    ),
                ),
                ("serie", models.CharField(max_length=10, verbose_name="Série")),
                (
                    "chave_acesso",
                    models.CharField(
                        blank=True,
                        max_length=44,
                        null=True,
                        verbose_name="Chave de Acesso",
                    ),
                ),
                ("data_emissao", models.DateField(verbose_name="Data de Emissão")),
                (
                    "data_recebimento",
                    models.DateField(verbose_name="Data de Recebimento"),
                ),
                (
                    "frete",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Valor do Frete",
                    ),
                ),
                (
                    "desconto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Valor do Desconto",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Total"
                    ),
                ),
                (
                    "documento_anexo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/nfs/",
                        verbose_name="Documento Anexado",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("CONFERIDA", "Conferida (Confirmada)"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Nota Fiscal",
                "verbose_name_plural": "Notas Fiscais",
            },
        ),
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificador",
                    models.CharField(max_length=100, verbose_name="Lote do Fabricante"),
                ),
                (
                    "data_fabricacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Fabricação"
                    ),
                ),
                (
                    "data_validade",
                    models.DateField(verbose_name="Validade Física do Produto"),
                ),
                (
                    "quantidade_inicial",
                    models.IntegerField(verbose_name="Quantidade Inicial"),
                ),
                (
                    "custo_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Custo Unitário"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Lote",
                "verbose_name_plural": "Lotes",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantidade")),
                (
                    "cost_unit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Custo Unitário Histórico",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("ENTRADA_COMPRA", "Entrada por Nota Fiscal"),
                            ("TRANSFERENCIA_SAIDA", "Transferência (Saída)"),
                            ("TRANSFERENCIA_ENTRADA", "Transferência (Entrada)"),
                            ("ENTREGA_COLABORADOR", "Entrega a Colaborador"),
                            ("DEVOLUCAO_COLABORADOR", "Devolução de Colaborador"),
                            ("AJUSTE_POSITIVO", "Ajuste de Entrada Manual"),
                            ("AJUSTE_NEGATIVO", "Ajuste de Saída Manual"),
                            ("BAIXA_DANO", "Baixa por Dano"),
                            ("BAIXA_PERDA", "Baixa por Perda"),
                            ("BAIXA_VENCIMENTO", "Baixa por Vencimento"),
                            ("ESTORNO", "Estorno Controlado"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Movimento",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observações/Justificativa"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data/Hora do Registro"
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Chave de Idempotência",
                    ),
                ),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID de Correlação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação de Estoque",
                "verbose_name_plural": "Movimentações de Estoque",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("EXPEDIDA", "Expedida (Em Trânsito)"),
                            ("RECEBIDA", "Recebida"),
                            ("RECEBIDA_COM_DIVERGENCIA", "Recebida com Divergência"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="RASCUNHO",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Expedição"
                    ),
                ),
                (
                    "recebido_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Recebimento"
                    ),
                ),
                (
                    "justificativa_divergencia",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Justificativa de Divergência/Observações",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transferência de Estoque",
                "verbose_name_plural": "Transferências de Estoque",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razao_social",
                    models.CharField(max_length=255, verbose_name="Razão Social"),
                ),
                (
                    "cnpj_cpf",
                    models.CharField(
                        max_length=18, unique=True, verbose_name="CNPJ/CPF"
                    ),
                ),
                (
                    "contato",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome de Contato",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-mail"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
            },
        ),
        migrations.CreateModel(
            name="StockTransferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_sent",
                    models.IntegerField(verbose_name="Quantidade Enviada"),
                ),
                (
                    "quantity_received",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Quantidade Recebida"
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.lot",
                        verbose_name="Lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Transferência",
                "verbose_name_plural": "Itens da Transferência",
            },
        ),
    ]
