# Generated by Django 4.2.27 on 2026-07-09 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("inventory", "0001_initial"),
        ("ppe", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransferitem",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ppe.productvariant",
                verbose_name="Variante de EPI",
            ),
        ),
        migrations.AddField(
            model_name="stocktransferitem",
            name="transfer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="inventory.stocktransfer",
                verbose_name="Transferência",
            ),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="criado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_transfers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Expedido por",
            ),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="dest_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dest_transfers",
                to="organizations.inventorylocation",
                verbose_name="Local de Destino",
            ),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="recebido_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="received_transfers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Recebido por",
            ),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="source_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_transfers",
                to="organizations.inventorylocation",
                verbose_name="Local de Origem",
            ),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfers",
                to="organizations.unit",
                verbose_name="Unidade",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="organizations.inventorylocation",
                verbose_name="Local de Estoque",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="lot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="inventory.lot",
                verbose_name="Lote",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="ppe.productvariant",
                verbose_name="Variante de EPI",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="organizations.unit",
                verbose_name="Unidade",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário Responsável",
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="fiscal_note",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lots",
                to="inventory.fiscalnote",
                verbose_name="Nota Fiscal",
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lots",
                to="ppe.productvariant",
                verbose_name="Variante de EPI",
            ),
        ),
        migrations.AddField(
            model_name="fiscalnote",
            name="centro_custo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fiscal_notes",
                to="organizations.costcenter",
                verbose_name="Centro de Custo",
            ),
        ),
        migrations.AddField(
            model_name="fiscalnote",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fiscal_notes",
                to="inventory.supplier",
                verbose_name="Fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="fiscalnote",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fiscal_notes",
                to="organizations.unit",
                verbose_name="Unidade Recebedora",
            ),
        ),
        migrations.AddField(
            model_name="fiscalnote",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fiscal_notes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registrado por",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stocktransferitem",
            unique_together={("transfer", "product_variant", "lot")},
        ),
        migrations.AlterUniqueTogether(
            name="lot",
            unique_together={("product_variant", "identificador")},
        ),
        migrations.AlterUniqueTogether(
            name="fiscalnote",
            unique_together={("supplier", "numero", "serie")},
        ),
    ]
