# Generated by Django 5.2.16 on 2026-07-10 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('ppe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalnote',
            name='tipo',
            field=models.CharField(choices=[('NOTA_FISCAL', 'Nota Fiscal'), ('RECIBO', 'Recibo'), ('SEM_DOCUMENTO', 'Sem documento'), ('OUTRO', 'Outro')], default='NOTA_FISCAL', max_length=20, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='lot',
            name='ca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ppe.certificadoaprovacao', verbose_name='C.A. (Certificado de Aprovação)'),
        ),
        migrations.AlterField(
            model_name='fiscalnote',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Documento'),
        ),
        migrations.AlterField(
            model_name='fiscalnote',
            name='serie',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Série'),
        ),
    ]
