# Generated by Django 5.2.16 on 2026-07-21 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_fiscalnote_tipo_lot_ca_alter_fiscalnote_numero_and_more'),
        ('organizations', '0002_alter_company_options'),
        ('ppe', '0005_alter_ppedelivery_status_assinatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationStockMinimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque_minimo', models.IntegerField(default=0, verbose_name='Estoque Mínimo')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_minimums', to='organizations.inventorylocation', verbose_name='Local de Estoque')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_minimums', to='ppe.productvariant', verbose_name='Variante de EPI')),
            ],
            options={
                'verbose_name': 'Estoque Mínimo por Local',
                'verbose_name_plural': 'Estoques Mínimos por Local',
                'unique_together': {('product_variant', 'location')},
            },
        ),
    ]
