# Generated by Django 5.2.16 on 2026-09-03 18:06

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_locationstockminimo'),
        ('organizations', '0002_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalnote',
            name='documento_anexo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/nfs/', validators=[inventory.models.validate_fiscal_note_attachment], verbose_name='Documento Anexado'),
        ),
        migrations.AlterField(
            model_name='fiscalnote',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='fiscalnote',
            name='serie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='fiscalnote',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CONFERIDA', 'Conferida e Integrada ao Estoque'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='fiscalnote',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_notes', to='organizations.unit', verbose_name='Unidade'),
        ),
    ]
