# Generated by Django 4.2.27 on 2026-07-09 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(max_length=255, verbose_name="Ação Executada"),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="Nome da Entidade"),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID do Objeto",
                    ),
                ),
                (
                    "changes_before",
                    models.TextField(
                        blank=True, null=True, verbose_name="Valores Anteriores"
                    ),
                ),
                (
                    "changes_after",
                    models.TextField(
                        blank=True, null=True, verbose_name="Valores Posteriores"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Navegador/User Agent",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Auditoria",
                "verbose_name_plural": "Registros de Auditoria",
                "ordering": ["-created_at"],
            },
        ),
    ]
