# Generated by Django 4.2.27 on 2026-07-09 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("ESTOQUE_BAIXO", "Estoque abaixo do Mínimo"),
                            ("LOTE_VENCIMENTO", "Lote Próximo do Vencimento"),
                            ("LOTE_VENCIDO", "Lote Vencido"),
                            ("CA_VENCIMENTO", "C.A. Próximo do Vencimento"),
                            ("CA_VENCIDO", "C.A. Vencido"),
                            (
                                "CA_NAO_VERIFICADO",
                                "C.A. não verificado ou desatualizado",
                            ),
                            ("TROCA_BREVE", "EPI de Colaborador próximo da troca"),
                            ("TROCA_VENCIDA", "EPI de Colaborador com troca vencida"),
                            (
                                "TRANSFERENCIA_PENDENTE",
                                "Transferência pendente de recebimento",
                            ),
                            ("FALTA_CIENCIA", "Entrega sem ciência/assinatura"),
                            ("DIVERGENCIA_ESTOQUE", "Divergência de estoque"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Alerta",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Informação"),
                            ("WARNING", "Aviso / Atenção"),
                            ("CRITICAL", "Crítico / Urgente"),
                        ],
                        default="INFO",
                        max_length=15,
                        verbose_name="Gravidade",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Título do Alerta"),
                ),
                ("message", models.TextField(verbose_name="Mensagem")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOVO", "Novo"),
                            ("LIDO", "Lido"),
                            ("RESOLVIDO", "Resolvido"),
                        ],
                        default="NOVO",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolvido em"
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="organizations.unit",
                        verbose_name="Unidade",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário Destinatário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta",
                "verbose_name_plural": "Alertas",
                "ordering": ["-created_at"],
            },
        ),
    ]
